const rockSongs = [
  "Accept - Amamos La Vida",
  "Accept - Seawinds",
  "Aerosmith - Amazing",
  "Aerosmith - Angel",
  "Aerosmith - Crazy",
  "Aerosmith - Cryin'",
  "Aerosmith - I Don't Want to Miss a Thing",
  "Aerosmith - Janie's Got A Gun",
  "Alias - More Than Words Can Say",
  "Atlantic Starr - Always",
  "Axel Rudi Pell - The Une",
  "Back Street Boys - I Want It That Way",
  "Bad English - When I See You Smile",
  "Barbra Streisand - Woman In Love",
  "Bee Gees - How Deep Is Your Love",
  "Billy Idol - Sweet Sixteen",
  "Black Sabbath - Nightwing",
  "Black Sabbath - She's Gone",
  "Blacksmith - The King Has Lost His Crown",
  "Blind Guardian - Nightfall",
  "Bob Dylan - Knockin' On Heaven's Door",
  "Bonfire - Give It A Try",
  "Bonfire - Goodnight Amanda",
  "Bonfire - Love Don't Lie",
  "Bon Jovi - Always",
  "Bon Jovi - Bed Of Roses",
  "Bon Jovi - Livin' On A Prayer",
  "Bon Jovi - Never Say Goodbye",
  "Bon Jovi - Thank You For Loving Me",
  "Bonnie Tyler - Total Eclipse of the Heart",
  "Bruce Dickinson - Tears Of The Dragon",
  "Bruce Springsteen - Streets Of Philadelphia",
  "Bryan Adams - Everything I Do",
  "Bryan Adams - Please Forgive Me",
  "CCR - Have You Ever Seen The Rain",
  "Celine Dion - That's the Way It Is",
  "Cheap Trick - The Flame",
  "Chicago - You're the Inspiration",
  "Chris Isaak - Can't Help Falling in Love",
  "Chris Isaak - Wicked Game",
  "Chris Rea - Josephine",
  "Chris Rea - Looking For The Summer",
  "Chris Rea - Nothing To Fear",
  "Cinderella - Coming Home",
  "Cinderella - Don't Know What You Got (Till It's Gone)",
  "Cinderella - Nobody's Fool",
  "Cinderella - Heartbreak Station",
  "Creedence - Have You Ever Seen The Rain",
  "Dan Hill - Never Thought (That I Could Love)",
  "Daniel Lopes - I Love you More than Yesterday",
  "Darxon - Don't Give Up",
  "Deep Purple - Soldier Of Fortune",
  "Def Leppard - Stand Up (Kick Love Into Motion)",
  "Def Leppard - Two Steps Behind",
  "Diana Ross - Upside Down",
  "DIO - All The Fools Sailed Away",
  "DIO - Between Two Hearts",
  "Dire Straits - Brothers In Arms",
  "Eagles - Hotel California",
  "Elton John - Sacrifice",
  "Enrique Iglesias & Whitney Houston - Could I Have This Kiss Forever",
  "Eric Clapton - Tears In Heaven",
  "Europe - Carrie",
  "Extreme - More Than Words",
  "Foreigner - I Want To Know What Love Is",
  "Foreigner - Waiting For A Girl Like You",
  "Gamma Ray - Pray",
  "Gary Moore - Still Got The Blues",
  "Gary Moore - Story Of The Blues",
  "Genesis - No Son Of Mine",
  "George Michael - One More Try",
  "Gorky Park - Stranger",
  "Great White - House Of Broken Love",
  "Guns N' Roses - Don't Cry",
  "Guns N' Roses - November Rain",
  "Guns N' Roses - Patience",
  "Guns N' Roses - Sweet Child O' Mine",
  "Hammerfall - Remember Yesterday",
  "Heart - Alone",
  "Helloween - A Tale That Wasn't Right",
  "Helloween - Forever & One (Neverland)",
  "Irene Cara - Flashdance ... What A Feeling",
  "Iron Maiden - Como Estais Amigos",
  "Iron Maiden - Wasting Love",
  "Iron Savior - After The War",
  "Joan Jett - I Love Rock n' Roll",
  "Joe Cocker - You Can Leave Your Hat On",
  "John Lennon - Woman",
  "Journey - Don't Stop Believin'",
  "Journey - Open Arms",
  "Kenny Rogers - Lady",
  "Kim Carnes - Bette Davis Eyes",
  "Kingdom Come - Janine",
  "Kingdom Come - What Love Can Be",
  "Kiss - Forever",
  "Kiss - God Gave Rock&Roll To You",
  "Kool & The Gang - Celebration",
  "Kreator - Golden Age",
  "Labirinth - Love",
  "Lacrimosa - Dich Zu Töten Fiel Mir Schwer",
  "Led Zeppelin - Immigrant Song",
  "Led Zeppelin - Stairway To Heaven",
  "Led Zeppelin - Whole Lotta Love",
  "Lionel Richie & Diana Ross - Endless Love",
  "Lionel Richie - Say You, Say Me",
  "Lionel Richie - Stuck on You",
  "Lipps Inc. - Funkytown",
  "Lobo - How Can I Tell Her",
  "Madonna - Like A Virgin",
  "Magnum - When The World Comes Down",
  "Manfred Mann - Questions",
  "Manowar - Courage",
  "Megadeth - Blood Of Heroes",
  "Metallica - Nothing Else Matters",
  "Metallica - The Unforgiven",
  "Michael Bolton - A Love so Beautiful",
  "Michael Bolton - Missing You Now",
  "Michael Bolton - Soul Provider",
  "Michael Bolton - When a Man Loves a Woman",
  "Michael Jackson - Beat It",
  "Michael Jackson - Billie Jean",
  "Mob Rules - Hold On",
  "Moonspell - Ghostosong",
  "Motley Crue - Without You",
  "Motley Crue - You're All I Need",
  "Mr.Big - Wild World",
  "MSG (Mcauley Schenker Group) - Time",
  "Nazareth - Dream On",
  "Nazareth - Love Hurts",
  "Nazareth - Love Leads To Madness",
  "Nazareth - We Are Animals",
  "Nazareth - Where Are You Now",
  "Night Ranger - Sister Christian",
  "Nightwish - Sleeping Sun",
  "Nostradameus - Without Your Love",
  "Olivia Newton-John - Magic",
  "Olivia Newton-John - Physical",
  "Ozzy Osbourne - Dreamer",
  "Ozzy Osbourne - I Just Want You",
  "Ozzy Osbourne - Mama, I'm Coming Home",
  "Patty Smyth & Don Henley - Sometimes Love Just Aint Enough",
  "Paul McCartney & Michael Jackson - Say, Say, Say",
  "Phenomena Ii - Did It All For Love",
  "Phil Collins - Against All Odds",
  "Pink Floyd - Another Brick in the Wall",
  "Pink Floyd - Shine On You Crazy Diamond",
  "Poison - Every Rose Has It's Thorn",
  "Poison - Something to Believe In",
  "Pretty Maids - Clay",
  "Pretty Maids - If It Can't Be Love",
  "Procol Harum - Whiter Shade Of Pale",
  "Queen - Another One Bites The Dust",
  "Queen - Bohemian Rhapsody",
  "Queen - Friends Will Be Friends",
  "Queen - Made In Heaven",
  "Queen - The Show Must Go On",
  "Quiet Riot - Don't Wanna Be Your Fool",
  "Radiohead - Creep",
  "Ratt - Givin' Yourself Away",
  "Red Hot Chili Peppers - Californication",
  "Red Hot Chili Peppers - Scar Tissue",
  "R.E.M. - Everybody Hurts",
  "R.E.M. - Losing My Religion",
  "REO Speedwagon - Can't Fight This feeling",
  "Reo Speedwagon - Keep On Loving",
  "Rhapsody - The Bloody Rage Of The Titans",
  "Rhapsody - Wings Of Destiny",
  "Richard Marx - Right Here Waiting",
  "Rick Astley - Never Gonna Give You Up",
  "Rick Astley - Take Me to Your Heart",
  "Rod Stewart - Have I Told You Lately",
  "Rolling Stones - Angie",
  "Rolling Stones - Anybody Seen My Baby",
  "Roxette - It Must Have Been Love",
  "Royal Hunt - Clown In The Mirror",
  "Royal Hunt - Follow Me",
  "Savage Garden - I Knew I Loved You",
  "Savage Garden - To The Moon & Back",
  "Savage Garden - Truly Madly Deeply",
  "Scorpions - Always Somewhere",
  "Scorpions - Believe In Love",
  "Scorpions - Holiday",
  "Scorpions - Send Me An Angel",
  "Scorpions - Still Loving You",
  "Scorpions - Wind Of Change",
  "Sinner - Destiny",
  "Slaughter - Fly to the Angels",
  "Smokie - Baby It's You",
  "Smokie - Living Next Door To Alice",
  "Smokie - Stranger",
  "Smokie - What Can I Do",
  "Sonata Arctica - Letter To Dana",
  "Soul Asylum - Runaway Train",
  "Status Quo - In The Army Now",
  "Steeler - The Deeper The Night",
  "Steelheart - I'll Never Let You Go",
  "Steelheart - She's Gone",
  "Stevie Wonder - I Just Called To Say I Love You",
  "Strangeways - Goodnight L.A.",
  "Stratovarius - 4000 Rainy Nights",
  "Styx - Boat On The River",
  "Survivor - Ever Since The World Began",
  "Survivor - Eye of the Tiger",
  "Survivor - The Search Is Over",
  "Sweet - Lady Starlight",
  "Talisman - All I Want",
  "Tesla - Love Song",
  "The Animals - House Of The Rising Sun",
  "The Doors - Riders On The Storm",
  "The Doors - The End",
  "The Guys Next Door - I've Been Waiting For You",
  "The Moody Blues - Night In White Satin",
  "The Police - Every Breath You Take",
  "Therion - The King",
  "Tiamat - Brighter Than the Sun",
  "Tiamat - Carry Your Cross and I'll Carry Mine",
  "Tiamat - Clovenhoof",
  "Tiamat - Do You Dream Of Me",
  "Tiamat - Gaia",
  "Tiamat - Love In Chains",
  "Tiamat - Wings Of Heaven",
  "Tim McMorris - Never Letting Go",
  "Tito & Tarantula - After Dark",
  "To/Die/For - Lacrimarum",
  "Tony Carey - Room With A View",
  "Twilight Guardians - Snowfall",
  "U2 - Beautiful Day",
  "U2 - One",
  "U2 - Pride (In The Name Of Love)",
  "U2 - With Or Without You",
  "UDO - In The Darkness",
  "Urge Overkill - Girl, You'll Be A Woman Soon",
  "Uriah Heep - Lady In Black",
  "Van Halen - Jump",
  "Warrant - I Saw Red",
  "W. A. S. P. - Sleeping",
  "Westlife - Beautiful in White",
  "Westlife - I Lay My Love on You",
  "Westlife - I Wanna Grow Old With You",
  "Westlife - My Love",
  "White Lion - Death Do Us Part",
  "White Lion - When The Children Cry",
  "Whitesnake - Is This Love",
  "ZZ Top - Rough Boy",
];

module.exports = rockSongs;
